### ISSUE TITLE
Handle infrastructure meltdown scenarios

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#354] opened 2019-11-12 18:30 UTC
## Issue
We have observed the situations where, due to infrastructure outages/issues, most of the machines in the cluster could become `unhealthy` simultaneously. In such cases, the MCM remediation system could kick-in and start trying to replace all affected machines. This would make the overall-state no better but actually worse.

## Probable Solution
We need to build a robust solution to handle such cases. One of the possible solutions could be to freeze the MCM when more than ~X% [~60%/70%] of the machines are unhealthy together.

**Comment by vlerenc** [comment] 2019-11-13 04:59
May be hard for small clusters (1 or 2 nodes would trigger melt-down protocol right away), but for larger clusters it becomes increasingly unlikely that they all fail. If at the moment we would tear down the machine (after the grace period), we see that 75 % or even only all machines (in a zone?) are also `NotReady`, then we can expect some general issue and freeze before we start making things even worse. The workload may be running perfectly well and even if it isn't for now, giving up the machine may later become a problem when we try to get a new one and many others want to. This time we have also seen issues that some machine types were unavailable when the infrastructure was well again.

Follow-up question is how to unfreeze again. When the nodes become `Ready`, unfreeze should happen automatically and again a grace period should prevent that if we go below the threshold, some machines that haven't yet reported back are not torn down too early, because they most likely will all come back online again.

**Comment by rfranzke** [comment] 2019-11-13 07:01
MCM should also check if the VM itself exists by asking the cloud provider. If it only freezes if 70% of the nodes are getting `NotReady`, then a manual deletion of multiple VMs (e.g., via cloud provider directly) may freeze MCM and without the possibility to ever unfreeze again.

**Comment by vlerenc** [comment] 2019-11-13 09:08
Well, first I would play it conservatively and if 100 % of the machines of one machine deployment (that means also zone, which may be crucial in these cases) become `NotReady`, then let's stop for the time being with remedy measures. Would that already be OK? Operations that are scheduled or would come from elsewhere (cluster autoscaler) would start/commence. A machine and node without a backing VM should be handled as usual. However, that would differ from a full freeze. Or is a full freeze better and if you guys opt for that, which operations would be frozen? Would the case of Rafael cause trouble? In any case, we also need logic for unfreeze that the end user can't break.

**Comment by amshuman-kr** [comment] 2019-11-13 10:27
The overall problem is larger than just the management of machines. While checking the loadbalancer issue, I found the following order of problems related to unreliable control-planes or infrastructures.

1. Nodes marked as `NotReady` if they are unresponsive for some time. This is controlled by the KCM flag `--node-monitor-grace-period duration     Default: 40s`.
_Amount of time which we allow running Node to be unresponsive before marking it unhealthy. Must be N times more than kubelet's nodeStatusUpdateFrequency, where N means number of retries allowed for kubelet to post node status_.

1. Pods on the `NotReady` nodes also immediately get marked as `NotReady` by the [`node_lifecycle_controller`](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1343). This does not seem to be configurable.
This cuts off the traffic from going to those pods.

1. Pods on the `NotReady` nodes are evicted at a configured rate. This is controlled by 3 KCM flags.

   1. `--node-eviction-rate float32     Default: 0.1`.
_Number of nodes per second on which pods are deleted in case of node failure when a zone is healthy (see --unhealthy-zone-threshold for definition of healthy/unhealthy). Zone refers to entire cluster in non-multizone clusters._
This applies if the cluster is considered _healthy_.

   1. Secondary Node eviction rate.`--secondary-node-eviction-rate float32     Default: 0.01`.
_Number of nodes per second on which pods are deleted in case of node failure when a zone is unhealthy (see --unhealthy-zone-threshold for definition of healthy/unhealthy). Zone refers to entire cluster in non-multizone clusters. This value is implicitly overridden to 0 if the cluster size is smaller than --large-cluster-size-threshold._
This applies if the cluster is considered _unhealthy_.

   1. When and why a cluster is considered to be _healthy_ or _unhealthy_ is controlled by the KCM flag  `--unhealthy-zone-threshold float32     Default: 0.55`.
_Fraction of Nodes in a zone which needs to be not Ready (minimum 3) for zone to be treated as unhealthy._
This is similar to the approach being suggested for MCM. This flag currently only influences pod eviction rate for the `NotReady` nodes. 

1. MCM tries to replace nodes that are continuously `NotReady` for some configured time.

This issue and the discussion so far are addressing only problem 4. This is very much required. But I think the overall problem requires a multi-layered solution.

1. We should tweak the KCM flags mentioned above to suit our (and stakeholders') needs.
1. We should consider contributing a new flag (may be two) to KCM to control problem 2 (marking of pods as `NotReady`) which is currently uncontrolled. Such an enhancement to KCM could possibly solve for the loadbalancer problem as well without a specific solution that we are working on. We can do this in multiple steps (i.e. after the current specific solution is done).
1. Enhance MCM freeze/unfreeze behaviour as being discussed in this issue.
1. Maybe we can think about introducing a `ClusterHealth` CRD to capture and publish known/identified cluster health issues which can act as a point of co-ordination for different control-plane components. The KCM and MCM flags will be local to those components and can only acted upon by those components. Also, they will duplicate the logic.
A more explicit resource can help different components co-ordinate both in the case the cluster becomes unhealthy as well as when it becomes healthy again. Also, this can help the components co-ordinate for more than one reason for the cluster's _illhealth_. We could even think about mass updating these resources in case we have some known landscape-wide or infrastructure-wide issue as a preventive measure.

**Comment by majst01** [comment] 2019-11-15 13:03
We suffered from the same event. Root cause was a internet outage on our side,  kube-api-server set nodes to `NotReady` and after 10min MCM started to delete all machines of our shooted seed, which was bad.

I would also like to suggest to check not only the KCM nodestatus, but also the machine status from cloud provider perspective, as @rfranzke suggested as well. I am aware of the fact that cloud provider status of the machine does not mean that the node from the kube-api perspective may differ and comming to a decision is hard.

**Comment by himanshu-kun** [comment] 2022-02-02 12:02
related to #679

**Comment by vlerenc** [comment] 2022-02-03 11:32
Instead of introducing a cluster health state or general freeze logic, we discussed to rather improve how dependency watchdog takes down KCM and MCM and ramps both up again (staged, i.e. some time after the API servers return KCM, and then some more time after KCM returns MCM) and slow down self-repair via a configurable parameter, e.g. `maxReplacements` effective per zone, so that melt-down events leave time for Kubelets/KCM to properly report their status again and not take all nodes down at the same time.

**Closed** 2022-03-22 07:39 UTC
Labels: priority/critical, kind/discussion, lifecycle/rotten, platform/all, component/mcm, roadmap/internal
