### ISSUE TITLE
One machine too many deleted when scaling down

### ISSUE THREAD

**Issue by vlerenc** [gardener/machine-controller-manager#81] opened 2018-05-09 14:44 UTC
I had scaled-out the dev/perf-load/pl-1 cluster for the performance team to 40 machines and then I scaled it down from 40 to 2. Strangely, instead of keeping 2 existing machines (my expectation), I only kept one. 39 machines got terminated and I got a new one instead to make up for the one that I shouldn't have lost. Do you have an explanation? We should try to keep the machine set as stable as possible and avoid unnecessary terminations and this looked like a termination that we should have avoided, wouldn't you agree?

**Comment by hardikdr** [comment] 2018-05-30 06:43
We should also check the bug here, where sometimes FrozenCondition is missing but freeze label exists on the MachineSet or vice versa.

**Comment by hardikdr** [comment] 2018-06-29 14:33
Hi Vedran,
Gaurav had been working on it recently, but could not really reproduce it, I also tried sometime back but dint help. We plan to get this bug resolved by next release.

**Comment by vlerenc** [comment] 2018-06-29 14:47
Thanks, I can reproduce it nicely:
- I create a standard shoot with two nodes and an older Kubernetes version, e.g. v1.9
- I upgrade the cluster to the next minor version, e.g. v1.10
I did that a couple of times and my `kubectl` watch always shows at one point in time only one v1.9 machine, then two v1.10 machines come back. Maybe this helps to reproduce the issue? Anyway, no real hurry, just thinking that it would be good to resolve it. People start noticing what we run more and more (now they question our forced security patch roll-outs - a valid question, AWS does it like we are doing it, but GKE only warns/recommends - maybe an option for us as well, but that's an entirely different topic; just mentioning it, because my impression is, we see more and more semi-productive workloads and some parties/software is not yet "optimally adapted" to Kubernetes, which is why we should make it even more stable).

**Comment by ggaurav10** [comment] 2018-06-29 19:56
Hi 
Is it possible that this is due to the value `spec.strategy.rollingUpdate.maxUnavailable` set to 1 (I believe this is the default) in machine deployment?
This value signifies the maximum number of nodes that can be unavailable out of the set number of replicas during rolling updates.

**Comment by vlerenc** [comment] 2018-06-30 05:49
Ah, now that you say it, this sounds like a reasonable explanation. However, the intention back then was somehow another, I believe. The new machines should be already `Ready`, before starting to drain the `maxUnavailable` number of machines (or more precisely?, for every machine that shall be drained a new `Ready` machine should be available, so that the scheduled pods find immediately a new node). Would do you think?

**Comment by ggaurav10** [comment] 2018-07-02 05:02
i skimmed through
https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/deployment_rolling.go

During rolling update, looks like we keep scaling up the new replica set until we can (which is based on total replicas under machine deployment <= replicas + maxSurge), and when this stage is reached, we start scaling down the old replica set.
Issue is that the scale down of old replica set begins as soon as the above comparison becomes false, without actually checking if those new machines joined the cluster or not (which takes few more seconds/minutes). For this much time, we see the total number of ready machines (kubernetes node objects) going down.
Will need to verify this code-analysis by trying out the scenario, and analyse the logs.

**Comment by ggaurav10** [comment] 2018-07-02 06:12
I think the issue is in the line:
https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/deployment_rolling.go#L134

```
maxScaledDown := allMachinesCount - minAvailable - newISUnavailableMachineCount
	if maxScaledDown <= 0 {
		return false, nil
	}
```
Instead of `allMachinesCount`, if we use `allReadyMachinesCount` (number of machines `ready`), then we wouldn't see this. Not sure what will be side-effects of this change. Will need to analyse some more and do thorough testing.
I am on leave this week, and thus won't be able to spend much time on this.

**Comment by vlerenc** [comment] 2018-07-17 12:40
Proposal for release note to be added:
```
Before this release, we allowed one machine to be unavailable during (OS) rolling update, which may have caused unavailable workload in clusters that are fully utilised. Now, during a rolling update, new machines will be added (and waited to get `Ready`), before old machines get drained and terminated. This way, the drained workload can be scheduled immediately on the new workers and the downtime is minimal or none (with proper Kubernetes pod disruption budgets).
```

**Comment by vlerenc** [comment] 2018-09-26 17:56
That's done, right?

**Comment by prashanth26** [comment] 2018-10-01 08:12
Hi @vlerenc,
    
We haven't been able to reproduce this issue again. Also, we haven't seen this issue occurring in any of the machine sets recently. I hope it has been resolved. We can close this issue for now, and reopen it if we ever see this again.

Thanks & Regards,
Prashanth

**Closed by prashanth26** 2018-10-01 08:12 UTC
Labels: component/machine-controller-manager, kind/bug, priority/critical

**Comment by vlerenc** [comment] 2018-10-02 03:45
Thanks, sure.
