### ISSUE TITLE
Delete a special node

### ISSUE THREAD

**Issue by qiffang** [gardener/machine-controller-manager#434] opened 2020-03-21 12:25 UTC
**What would you like to be added**:
Hi @rfranzke , sorry to bother you.
I want to scale in the worker number by deleting a special vm (aws ec2)  by the node name or ec2 name.
What should I do? 

**Why is this needed**:
I deploy statefulset in shoot cluster and 1 pod with 1 vm.
When i update the replica of statefulset, the pod will be scaled in by statefulset. And I want to delete the special vm which running the deleted pod by  ec2 name or node name.

Thanks

**Comment by rfranzke** [comment] 2020-03-21 13:26
Closing as duplicate of #435

**Closed by rfranzke** 2020-03-21 13:26 UTC
Labels: kind/enhancement
