### ISSUE TITLE
Zone aware node autoscaling in multi-AZ cluster

### ISSUE THREAD

**Issue by pvpratyush** [gardener/machine-controller-manager#234] opened 2019-02-28 09:14 UTC
For a service to support multi-AZ paradigm, it is required that the pods of that service belongs to different zones, provided the number of pods of a service is less than or equal to the number of zones in a region. 

For example, there is a service which deploys 2 pods (P1, P2) and we have 3 zones (Z1,Z2,Z3). Suppose P1 is scheduled in Z1 then P2 must be scheduled on a node in Z2 or Z3, which means there must be a node available on Z2 or Z3.

Currently node autoscaler does not support zone aware scaling of nodes. This gives rise to a situation where provisioning of a service will be starved, if the autoscaler scales the node in the same zone or completely fails to scale up.

Another use case for zone aware autoscaling of nodes is, if we want the number of pods scheduled across zones to be balanced in a multi-AZ cluster. For this to de done efficiently, it is required that nodes are available in all zones.

**Comment by prashanth26** [comment] 2019-02-28 09:21
Thank you @pvpratyush for creating this issue. We shall definitely look into it, make changes and get back to you on this.

**Comment by prashanth26** [comment] 2019-06-25 06:25
Refer - https://github.com/kubernetes/autoscaler/blob/d4a6664b389b052293de8f2c0d16839564911e1f/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up. 

I think that the `--balance-similar-node-groups` should help us in achieving this.

**Comment by hardikdr** [comment] 2019-08-27 09:11
With some basic investigation, it seems the flag in CA `--balance-similar-node-groups` can satisfy the overall requirement given a few considerations from Gardener.
- Refer [link](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler) for quick understanding of the flag.


This flag basically allows Autoscaler to balance the number of machines across `Similar NodeGroups`. 
Similar Nodegroups are defined as:
1. Nodegroups having exactly equal `resource.Capacity`.
1. Nodegroups having exactly _**same labels**_ ignoring system-labels such as `kubernetes.io/hostname`, `failure-domain.beta.kubernetes.io/zone`, `failure-domain.beta.kubernetes.io/region`  [link](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go#L93)
1. Nodegroups having lesser difference-ratio than defined in `MaxAllocatableDifferenceRatio`, `MaxFreeDifferenceRatio`. [link to detail](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go#L29)

Also important to mention that, node-groups are balanced only while scaling-up, and not while scaling-down. This means node-groups might be unbalanced due to uneven distribution of workload due to scale-down.

For Gardener to consume this feature, the focus is only required on point`[2]` above, as Gardener sets certain worker-group labels on each node-objects. These custom labels added by Gardener being different - may violate the condition for similar-node groups.
- This can be resolved easily by enhancing/patching CA to also ignore the worker-group specific label [here](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go#L94-L103).
- Or patch Gardener to convert the worker-groups labels into annotations on node-object.

**Comment by hardikdr** [comment] 2019-08-29 09:22
As it seems, in order to enable the autoscaler to balance similar node-groups, we need to ensure that default-labels on nodes are the same[given similar characteristics]. 

Currently, we have at least 2 labels - `worker.garden.sapcloud.io/group`, `worker.gardener.cloud/pool` , being put by Gardener by default on each node.
There seem to be 2 different approaches to resolve it:
1. Changes at Gardener:
   - Gardener stops setting these labels altogether. 
       - We need to understand if Gardener relies/plan-to-rely on these labels, and what could be consequences otherwise. 
    - Or Gardener sets annotations instead of labels with the same information. 


2. Changes at Autoscaler:
   - We update the core of autoscaler to also ignore these specific workergroup-labels along with system-labels while balancing node-groups. [link](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go#L94-L103)
      - We need to understand that, autoscaler then diverges from upstream implementation.


@rfranzke It would be nice to have insights from you, specifically for possibilities around Approach 1.
cc @prashanth26 @amshuman-kr

**Comment by rfranzke** [comment] 2019-08-29 09:27
> We need to understand if Gardener relies/plan-to-rely on these labels, and what could be consequences otherwise.

Gardener doesn't need them at all. The labels are added for the end-users such that they can identify which node corresponds to which pool. I'm not sure if everybody is using/relying on it.

> Or Gardener sets annotations instead of labels with the same information.

The labels are added via `--node-labels` flag kubelet, I don't think there is a flag for annotations, so I guess that's not possible/no option.

**Comment by amshuman-kr** [comment] 2019-08-29 09:30
> Gardener doesn't need them at all. The labels are added for the end-users such that they can identify which node corresponds to which pool. I'm not sure if everybody is using/relying on it.

Now with the support for taints, labels and annotations in MCM, end users can do this and more without having to rely on worker-(pool|group) labels. Would it be OK to deprecate/delete these labels?

**Comment by rfranzke** [comment] 2019-08-29 09:32
Yes, valid point. Sure, sounds reasonable as we anyway have the replacement as you mentioned. 👍

**Comment by hardikdr** [comment] 2019-08-29 09:42
Perfect, I will do a few minor checks to verify if balancing works as expected in CA.
Then I will go ahead with removing these `--node-labels` , and enabling the `----balance-similar-node-groups` in autoscaler.

**Comment by hardikdr** [comment] 2019-09-05 11:00
I tried testing the balancing-feature, but it doesn't seem to be working as expected.

Basically CA checks for exactly same `Node.Status.Capacity.Memory`, to consider 2 node groups to be  `SimilarNodegroups`.  
   - The issue is, slightly different values have been consistently observed in `Node.Status.Capacity.Memory` for the nodes which are backed by exactly the same instance-types[eg m4.large].  It could be due to kubelet scrapping/posting different values for the capacity resource.
   - Autoscaler then does not see the node-groups similar and hence balancing is not seen as excepted.

This requires a patch in the core of upstream autoscaler to ignore small differences while matching the capacity. 
- Slack discussion: https://kubernetes.slack.com/archives/C09R1LV8S/p1567672487051200
- Openshift's patch: https://github.com/openshift/kubernetes-autoscaler/pull/113

**Comment by prashanth26** [comment] 2019-09-16 06:01
Needs new CA release to fix it on Gardener.

**Comment by prashanth26** [comment] 2020-08-13 20:50
Closing as MCM supports this feature with the help of cluster autoscaler today.

**Closed by prashanth26** 2020-08-13 20:50 UTC
Labels: area/high-availability, component/mcm, exp/intermediate, kind/enhancement, lifecycle/rotten, platform/all, priority/normal, size/m, status/new, topology/seed
