### ISSUE TITLE
MCM adds an extra taint (PreferNoSchedule) on nodes

### ISSUE THREAD

**Issue by PadmaB** [gardener/machine-controller-manager#277] opened 2019-06-11 05:02 UTC
It was observed that cluster using taints functionality had the following taint on most of its nodes, though it was not defined in the Shoot spec:

{
   “effect”: “PreferNoSchedule”,
   “key”: “deployment.machine.sapcloud.io/prefer-no-schedule”,
   “value”: “True”
 }

Since it was not able to identify the issue, the taint was manually deleted from the affected nodes. Logging this issue to investigate further

**Comment by prashanth26** [comment] 2019-06-18 07:52
Hi @PadmaB ,

This taint would've possibly been added by MCM on older worker pools during a rolling update to avoid scheduling on pods on older worker nodes. More details can be found here - https://github.com/gardener/machine-controller-manager/pull/202/. 

Also is there a running cluster where you are observing nodes with such taints? I just wanted to have a look at it.

**Comment by hardikdr** [comment] 2019-06-18 08:37
>This taint would've possibly been added by MCM on older worker pools during a rolling update

Yes, I believe that's the only case when MCM adds such taint on machines.

I think the cluster is not available in a faulty-state anymore.  I had to manually remove the taints for the time being. Although the cluster wasn't going thru the rolling update as such, I could see only one machine-set backing the machine-deployment.

**Comment by prashanth26** [comment] 2019-06-26 11:12
We are unable to reproduce this issue currently, hence parking it for now. Please comment on this issue, if it re-surfaces.

**Comment by prashanth26** [comment] 2019-09-10 05:46
Closing this issue for now as it isn't reproducible. Please reopen if observed again.

**Closed by prashanth26** 2019-09-10 05:46 UTC
Labels: component/machine-controller-manager, kind/bug, triage/not-reproducible
