### ISSUE TITLE
Error when updating Machine status

### ISSUE THREAD

**Issue by timuthy** [gardener/machine-controller-manager#642] opened 2021-08-24 13:25 UTC
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
The machine status cannot be updated for the following reason:

```
Update failed for machine "shoot--dev--shoot-cpu-worker-z1-ff5c8-48vbl". Retrying, error: "Machine.machine.sapcloud.io \"shoot--dev--shoot-cpu-worker-z1-ff5c8-48vbl\" is invalid: status.conditions.lastHeartbeatTime: Invalid value: \"null\": status.conditions.lastHeartbeatTime in body must be of type string: \"null\""
```
The issue disappears as soon as the `lastHeartbeatTime` of the respective node conditions are maintained.

**What you expected to happen**:
The status update should work from the beginning.

**How to reproduce it (as minimally and precisely as possible)**:
- Apply the CRD definition of the main branch (e096125464b441d9ff403803c285ed206877d08c)
- Create a new `Machine`

**Possible soln**
Patch() seems to solve the issue rather than UpdateStatus() or Update() . Look at https://github.com/gardener/gardener/issues/5376

**Comment by plkokanov** [comment] 2022-02-02 12:19
btw I managed to find this issue today that seems loosely relevant https://github.com/kubernetes/kubernetes/issues/99804

**Comment by timebertt** [comment] 2022-02-03 08:06
Shouldn't the `metav1.Time` fields in `MachineStatus` be pointers if they are tagged with `omitempty`?

**Comment by plkokanov** [comment] 2022-02-03 09:31
Dug up this issue as well: https://github.com/kubernetes/kubernetes/issues/86811 which I guess is the same problem
Making the values pointers would be ok, but then checks if the fields are nil would have to be introduced.
And as far as I understand from [this comment](https://github.com/kubernetes/kubernetes/issues/86811#issuecomment-808932761) this should be fixed in k/k 1.20 (I only managed to reproduce this issue on 1.18 and 1.19)

**Comment by plkokanov** [comment] 2022-02-03 12:27
Before updating the machine crd with one generated with `// +nullable` for the `metav1.Time` fields the following call returns the error from the issue (btw when `metav1.Time` is not set, it is represented as null when marshalled to json):
```
k gardener patch-status\
  -n shoot--garden--migration3 machine shoot--garden--migration3-gardenlinux-z1-6fb56-q4hmx\
  --type=json --patch='[{ "op": "replace", "path": "/status", "value": {"lastOperation":{"lastUpdateTime":null}}}]'
```

After updating the crd so that `metav1.Time` fields are nullable the above call successfully modifies the status.

**Comment by himanshu-kun** [comment] 2023-02-15 05:52
/close
The issue is only seen in control cluster with k8s version < 1.20 (https://github.com/kubernetes/kubernetes/issues/86811) . For g/g we have already moved to much latest releases of k8s. So we won't be fixing this. If you are using mcm without gardener , then switch you control cluster to latest k8s version.

**Closed by himanshu-kun** 2023-02-15 05:52 UTC
Labels: kind/bug, lifecycle/rotten, area/robustness, priority/3
