### ISSUE TITLE
Improve deletion logic of machines

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#350] opened 2019-11-04 08:50 UTC
## Issue
Currently, while deleting the machine-object, machine-controller checks for the `ProviderID` field.
   - If the `ProviderID` field is empty, MCM simply assumes machine-creation failed and deletes the machine-object. [refer](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machine.go#L488-L610) 

This makes the behavior of the machine-controller binary in terms of the deletion of a machine.

0. Machine-creation failed, `ProviderID` is unset.
1. Machine-creation succeded, `ProviderID` is set.

The issue is, for providers like Azure, overall machine-creation could fail, but there could still be few resources spawned in the back-end. MCM currently has no way to identify such a scenario and tackle it.
- This is because we create/delete the VM/NIC/Disk individually in **azure** due to the nature of the **SDK**.  
 
PS: There is an attempt to partially solve this issue [here](https://github.com/gardener/machine-controller-manager/pull/347)

## Probable Solution
We need to enable MCM to tackle the scenario mentioned above.  One of the solutions could be to enhance the logic [here](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machine.go#L341-L357), to handle the case where, `err != nil && valid(actualProviderID)==true` 

Open for discussions/suggestions.

cc @prashanth26

**Comment by prashanth26** [comment] 2019-11-04 09:31
I think one simple way to solve this would be to check for any VMs on infra with matching tags before deleting the machine object. Hence we could combine solving this issue with - https://github.com/gardener/machine-controller-manager/issues/349

**Comment by ggaurav10** [comment] 2019-11-04 09:33
Another possible solution:
Implement the solution mentioned [here](https://github.com/gardener/machine-controller-manager/pull/347#issuecomment-547802082) by @prashanth26, and enhance safety controller's [`checkAzureMachineClass()`](https://github.com/gardener/machine-controller-manager/blob/rel-0.21.0/pkg/controller/machine_safety.go#L457) to check for orphan NICs/Disk too.

This will also solve the issue of orphan resources across MCM crashes/restarts. WDYT?

**Comment by prashanth26** [comment] 2019-11-04 09:38
> Another possible solution:
> Implement the solution mentioned [here](https://github.com/gardener/machine-controller-manager/pull/347#issuecomment-547802082) by @prashanth26, and enhance safety controller's [`checkAzureMachineClass()`](https://github.com/gardener/machine-controller-manager/blob/rel-0.21.0/pkg/controller/machine_safety.go#L457) to check for orphan NICs/Disk too.
> 
> This will also solve the issue of orphan resources across MCM crashes/restarts. WDYT?

Gaurav we already do that in the orphan VM logic. We do check for orphan NICs/Disks independent of VMs.

**Comment by ggaurav10** [comment] 2019-11-04 14:50
> Gaurav we already do that in the orphan VM logic. We do check for orphan NICs/Disks independent of VMs.

ah cool. Got confused by `getVMs()` which gets resources even for orphan NICs/disks

**Comment by hardikdr** [comment] 2019-11-05 06:24
> I think one simple way to solve this would be to check for any VMs on infra with matching tags before deleting the machine object. Hence we could combine solving this issue with - #349

This sounds like a good idea, we may go in this direction then. I'd still prefer to keep this issue open as the tagged issue above is more about fixing the creation, and this is about fixing the deletion flow, there will be corresponding differences in solution.

**Comment by prashanth26** [comment] 2019-11-05 06:29
Cool sounds good.

**Comment by prashanth26** [comment] 2019-11-13 10:23
Shall be fixing this issue with the #178 changes.

**Comment by prashanth26** [comment] 2020-08-13 21:11
Closing in favour of changes on OOT - https://github.com/gardener/machine-controller-manager/pull/460.

**Closed by prashanth26** 2020-08-13 21:11 UTC
Labels: component/mcm, lifecycle/rotten

**Comment by hardikdr** [comment] 2020-08-14 03:32
This was also fixed part of the : https://github.com/gardener/machine-controller-manager/pull/432 .
@prashanth26 I believe this is a critical behavior change, can you please confirm if this is adopted in the out of tree machine-controller.

**Comment by prashanth26** [comment] 2020-08-14 03:57
So the OOT basically checks for any VM first and then triggers the deletion of VMs. The same applies to creation. I hope this is what was intended with opening this issue?
